import type { NodeDefinition } from '../types'

export const bleCharacteristicNode: NodeDefinition = {
  id: 'ble-characteristic',
  name: 'BLE Characteristic',
  version: '1.0.0',
  category: 'connectivity',
  description: 'Read, write, and subscribe to BLE characteristic values',
  icon: 'radio-receiver',
  platforms: ['web', 'electron'],
  inputs: [
    { id: 'device', type: 'data', label: 'Device' },
    { id: 'read', type: 'trigger', label: 'Read' },
    { id: 'write', type: 'data', label: 'Write Data' },
    { id: 'writeTrigger', type: 'trigger', label: 'Write Trigger' },
  ],
  outputs: [
    { id: 'value', type: 'any', label: 'Value' },
    { id: 'rawValue', type: 'data', label: 'Raw Value' },
    { id: 'text', type: 'string', label: 'Text' },
    { id: 'formatted', type: 'string', label: 'Formatted' },
    { id: 'notified', type: 'trigger', label: 'Notified' },
    { id: 'properties', type: 'data', label: 'Properties' },
    { id: 'error', type: 'string', label: 'Error' },
  ],
  controls: [
    {
      id: 'serviceUUID',
      type: 'text',
      label: 'Service UUID',
      default: '',
      props: { placeholder: 'e.g., 180d or 0000180d-...' },
    },
    {
      id: 'characteristicUUID',
      type: 'text',
      label: 'Characteristic UUID',
      default: '',
      props: { placeholder: 'e.g., 2a37 or 00002a37-...' },
    },
    {
      id: 'dataFormat',
      type: 'select',
      label: 'Data Format',
      default: 'auto',
      props: {
        options: [
          { label: 'Auto (Use Profile)', value: 'auto' },
          { label: 'Unsigned 8-bit', value: 'uint8' },
          { label: 'Signed 8-bit', value: 'int8' },
          { label: 'Unsigned 16-bit', value: 'uint16' },
          { label: 'Signed 16-bit', value: 'int16' },
          { label: 'Unsigned 32-bit', value: 'uint32' },
          { label: 'Signed 32-bit', value: 'int32' },
          { label: 'Float 32-bit', value: 'float32' },
          { label: 'Float 64-bit', value: 'float64' },
          { label: 'UTF-8 String', value: 'utf8' },
          { label: 'Raw Bytes', value: 'raw' },
        ],
      },
    },
    {
      id: 'enableNotifications',
      type: 'toggle',
      label: 'Enable Notifications',
      default: true,
    },
    {
      id: 'continuous',
      type: 'toggle',
      label: 'Continuous Read',
      default: false,
    },
  ],
}
